// Code generated by ts2go batch. DO NOT EDIT.

package grammars

import "github.com/odvcencio/gotreesitter"

func AdaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("ada.bin")
}

func AgdaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("agda.bin")
}

func AngularLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("angular.bin")
}

func ApexLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("apex.bin")
}

func ArduinoLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("arduino.bin")
}

func AsmLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("asm.bin")
}

func AstroLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("astro.bin")
}

func AuthzedLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("authzed.bin")
}

func AwkLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("awk.bin")
}

func BashLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("bash.bin")
}

func BassLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("bass.bin")
}

func BeancountLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("beancount.bin")
}

func BibtexLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("bibtex.bin")
}

func BicepLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("bicep.bin")
}

func BitbakeLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("bitbake.bin")
}

func BladeLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("blade.bin")
}

func BrightscriptLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("brightscript.bin")
}

func CLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("c.bin")
}

func CSharpLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("c_sharp.bin")
}

func CaddyLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("caddy.bin")
}

func CairoLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("cairo.bin")
}

func CapnpLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("capnp.bin")
}

func ChatitoLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("chatito.bin")
}

func CircomLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("circom.bin")
}

func CmakeLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("cmake.bin")
}

func CommentLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("comment.bin")
}

func CommonlispLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("commonlisp.bin")
}

func CooklangLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("cooklang.bin")
}

func CornLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("corn.bin")
}

func CponLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("cpon.bin")
}

func CppLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("cpp.bin")
}

func CssLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("css.bin")
}

func CsvLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("csv.bin")
}

func CudaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("cuda.bin")
}

func CueLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("cue.bin")
}

func CylcLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("cylc.bin")
}

func DLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("d.bin")
}

func DartLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("dart.bin")
}

func DesktopLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("desktop.bin")
}

func DevicetreeLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("devicetree.bin")
}

func DiffLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("diff.bin")
}

func DisassemblyLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("disassembly.bin")
}

func DjotLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("djot.bin")
}

func DockerfileLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("dockerfile.bin")
}

func DoxygenLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("doxygen.bin")
}

func DtdLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("dtd.bin")
}

func EarthfileLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("earthfile.bin")
}

func EbnfLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("ebnf.bin")
}

func EditorconfigLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("editorconfig.bin")
}

func EdsLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("eds.bin")
}

func EexLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("eex.bin")
}

func ElixirLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("elixir.bin")
}

func ElmLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("elm.bin")
}

func ElsaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("elsa.bin")
}

func EmbeddedTemplateLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("embedded_template.bin")
}

func EnforceLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("enforce.bin")
}

func ErlangLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("erlang.bin")
}

func FacilityLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("facility.bin")
}

func FaustLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("faust.bin")
}

func FennelLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("fennel.bin")
}

func FidlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("fidl.bin")
}

func FirrtlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("firrtl.bin")
}

func FoamLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("foam.bin")
}

func GoLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("go.bin")
}

func GraphqlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("graphql.bin")
}

func HaskellLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("haskell.bin")
}

func HclLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("hcl.bin")
}

func HtmlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("html.bin")
}

func JavaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("java.bin")
}

func JavascriptLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("javascript.bin")
}

func JsonLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("json.bin")
}

func JuliaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("julia.bin")
}

func KotlinLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("kotlin.bin")
}

func LuaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("lua.bin")
}

func NixLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("nix.bin")
}

func OcamlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("ocaml.bin")
}

func PhpLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("php.bin")
}

func PythonLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("python.bin")
}

func RegexLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("regex.bin")
}

func RubyLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("ruby.bin")
}

func RustLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("rust.bin")
}

func ScalaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("scala.bin")
}

func SqlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("sql.bin")
}

func SwiftLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("swift.bin")
}

func TomlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("toml.bin")
}

func TsxLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("tsx.bin")
}

func TypescriptLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("typescript.bin")
}

func VerilogLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("verilog.bin")
}

func YamlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("yaml.bin")
}

func ZigLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("zig.bin")
}
