package grammars

import "github.com/odvcencio/gotreesitter"

// scanner_attachments.go — NOT generated by ts2go batch.
//
// This file re-attaches hand-written external scanners to their
// respective Language objects. Because ts2go batch overwrites
// *_register.go files on every regen, any ExternalScanner wiring
// placed there would be lost. Keeping it here means scanners survive
// future batch runs.
//
// init() order within a Go package is alphabetical by filename.
// This file starts with "zzz_" to ensure it runs AFTER all
// *_register.go files, so registry entries exist when this init runs.

func init() {
	attachments := map[string]gotreesitter.ExternalScanner{
		"python":  PythonExternalScanner{},
		"elixir":  ElixirExternalScanner{},
		"comment": CommentExternalScanner{},
		"doxygen": DoxygenExternalScanner{},
		"foam":    FoamExternalScanner{},
		"nginx":   NginxExternalScanner{},
		"nushell": NushellExternalScanner{},
		"r":       RExternalScanner{},
		"xml":        XMLExternalScanner{},
		"yuck":       YuckExternalScanner{},
		"purescript": PurescriptExternalScanner{},
		"typst":      TypstExternalScanner{},
	}

	for i := range registry {
		if scanner, ok := attachments[registry[i].Name]; ok {
			orig := registry[i].Language
			s := scanner // capture for closure
			registry[i].Language = func() *gotreesitter.Language {
				lang := orig()
				lang.ExternalScanner = s
				return lang
			}
		}
	}
}
